services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]
    _defaults:
        autoconfigure: true

    ContaoThemesNet\MateThemeBundle\Migration\Version300Update:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
